### ISSUE TITLE
Новые функции

### ISSUE THREAD

**Issue by luciql33t** [ManKwang/amino-bot#5]
Сообственно, предложения таковы:
1) Результат работы бота (а именно нарушения) - выводить не в консоль, а в чат (амино или телеграмм) для более простой работы команды администраторов.
Это из реальных. Из тех, что звучат фантастически:
1) Сделать счётчик нарушений каждого пользователя. После определенного количества нарушений - кик.

**Comment by SerhiiMandrykin** [comment]
Всё реализуемо. На счёт кика не уверен но, если например будет больше 3х нарушений бот может сообщать об этом в телеграмм

**Comment by luciql33t** [comment]
Ну тогда кик не нужен. Лучше рили сообщение в телеге или амино (общем чате). Так было бы получше.

**Comment by luciql33t** [comment]
А ещё, чтоб указывало в каком именно чате было нарушение. Это гораздо упростит всё.
