### ISSUE TITLE
Бот перестает отвечать на триггеры в чате

### ISSUE THREAD

**Issue by LynxN1** [ManKwang/amino-bot#8]
Через пару минут работы он перестает отвечать на триггеры в чате. Я подумал что слетает авторизация, проверил, всё работает. Не знаю в чем проблема.

**Comment by raidzin** [comment]
Аналогичная проблема. 
Как мне кажется прекращает работу цикл:
`for_ i in self.selected_chats:`
В файле MessageHandler.py  56я строка

**Comment by LynxN1** [comment]
> Аналогичная проблема.
> Как мне кажется прекращает работу цикл:
> `for_ i in self.selected_chats:`
> В файле MessageHandler.py 56я строка

Уже решил проблему, просто установи новую версию API. и подгони код под неё

**Comment by SerhiiMandrykin** [comment]
А можно детальнее описать проблему? Буду благодарен

**Comment by raidzin** [comment]
> 
> 
> > Аналогичная проблема.
> > Как мне кажется прекращает работу цикл:
> > `for_ i in self.selected_chats:`
> > В файле MessageHandler.py 56я строка
> 
> Уже решил проблему, просто установи новую версию API. и подгони код под неё

Пробовал, не помогло, возможно недостаточно хорошо "подогнал код"

**Comment by raidzin** [comment]
> 
> 
> А можно детальнее описать проблему? Буду благодарен

Бот просто не откликается на слова в чате, хотя при этом программа вроде как работает

**Comment by SerhiiMandrykin** [comment]
> > А можно детальнее описать проблему? Буду благодарен
> 
> Бот просто не откликается на слова в чате, хотя при этом программа вроде как работает

Как вы решили эту проблему? Буду рад пул реквестам))

**Comment by LynxN1** [comment]
> > > А можно детальнее описать проблему? Буду благодарен
> > 
> > 
> > Бот просто не откликается на слова в чате, хотя при этом программа вроде как работает
> 
> Как вы решили эту проблему? Буду рад пул реквестам))

В вашем боте используется старая версия API от Slimakoi, в новой версии больше плюшек в sub_client и переработаны функции login и logout, как и много чего другого. Это дает много новых возможностей для бота, так что буду ждать новую версию от вас!

**Comment by SerhiiMandrykin** [comment]
Please check V2 branch
